name: Validate-YAML

on:
  push:
    paths:
      - 'kind/manifests/**'
      - 'OCI/manifests/**'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Validate YAML file
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: kind/manifests/**.yaml OCI/manifests/**.yaml
          config_file: '.github/workflows/config.yamllint'